baseURL = 'https://tomdstanton.github.io/'
languageCode = 'en-us'
title = "Tom Stanton's blog"
theme = 'hugo-theme-stack'
copyright = "Thomas David Stanton"
DefaultContentLanguage = "en"
hasCJKLanguage = false
disqusShortname = "tomdstanton"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "G-38T9SV0JKL"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[pagination]
pagerSize = 3

[permalinks]
post = "/p/:slug/"
page = "/:slug/"

[params]
mainSections = [ "post" ]
featuredImageField = "image"
rssFullContent = true

  [params.footer]
  since = 2_020

  [params.dateFormat]
  published = "Jan 02, 2006"
  lastUpdated = "Jan 02, 2006 15:04 MST"

  [params.sidebar]
  emoji = "🍥"
  subtitle = "A dangerous mix of personal and professional opinions"

    [params.sidebar.avatar]
    enabled = true
    local = true
    src = "avatar.png"

  [params.article]
  math = false
  toc = true
  readingTime = true

    [params.article.license]
    enabled = true
    default = "Licensed under CC BY-NC-SA 4.0"

[[params.widgets.homepage]]
type = "search"

[[params.widgets.homepage]]
type = "tag-cloud"

  [params.widgets.homepage.params]
  limit = 10

[[params.widgets.page]]
type = "toc"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
main = [ ]

  [[menu.social]]
  identifier = "github"
  name = "GitHub"
  url = "https://github.com/tomdstanton"

    [menu.social.params]
    icon = "brand-github"

[related]
includeNewer = true
threshold = 60
toLower = false

  [[related.indices]]
  name = "tags"
  weight = 100

  [[related.indices]]
  name = "categories"
  weight = 200
